# Generated by Django 3.1.2 on 2020-10-18 13:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0002_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='blacklist',
            unique_together={('blocking_user', 'blocked_user', 'deleted_at')},
        ),
        migrations.RemoveField(
            model_name='blacklist',
            name='is_deleted',
        ),
    ]
